function cookie(req,name){const c=req.headers.get('Cookie')||'';return c.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)}
function dec(v){if(!v)return null;try{return JSON.parse(decodeURIComponent(escape(atob(v.replace(/-/g,'+').replace(/_/g,'/')))))}catch{return null}}
function enc(o){return btoa(unescape(encodeURIComponent(JSON.stringify(o)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function refresh(auth,env){if(auth.expires_at>Date.now()+60000)return {auth,setCookie:null};if(!auth.refresh_token)throw new Error('Session expired. Please sign in again.');const params={client_id:env.GOOGLE_CLIENT_ID,grant_type:'refresh_token',refresh_token:auth.refresh_token};if(env.GOOGLE_CLIENT_SECRET)params.client_secret=env.GOOGLE_CLIENT_SECRET;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)});const j=await r.json();if(!r.ok)throw new Error('Could not refresh Google session: '+JSON.stringify(j));auth.access_token=j.access_token;auth.expires_at=Date.now()+(j.expires_in||3600)*1000;return {auth,setCookie:`IA_AUTH=${enc(auth)}; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=2592000`}}
async function g(auth,method,url,body,headers={}){const r=await fetch(url,{method,headers:{Authorization:`Bearer ${auth.access_token}`,...headers},body});const text=await r.text();let j;try{j=JSON.parse(text)}catch{j=text}if(!r.ok)throw new Error(typeof j==='string'?j:JSON.stringify(j));return j}
function q(s){return s.replace(/'/g,"\\'")}
async function findFolder(auth,name,parent){const params=new URLSearchParams({q:`mimeType='application/vnd.google-apps.folder' and name='${q(name)}' and '${parent||'root'}' in parents and trashed=false`,fields:'files(id,name)'});const j=await g(auth,'GET','https://www.googleapis.com/drive/v3/files?'+params);return j.files?.[0]?.id}
async function createFolder(auth,name,parent,props={}){const meta={name,mimeType:'application/vnd.google-apps.folder',parents:[parent||'root'],appProperties:props};const j=await g(auth,'POST','https://www.googleapis.com/drive/v3/files?fields=id,name',JSON.stringify(meta),{'Content-Type':'application/json'});return j.id}
async function ensureFolder(auth,name,parent,props){return await findFolder(auth,name,parent)||await createFolder(auth,name,parent,props)}
function dataToBytes(dataUrl){const comma=dataUrl.indexOf(',');const b64=comma>=0?dataUrl.slice(comma+1):dataUrl;const bin=atob(b64);const arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return arr}
async function findFile(auth,name,parent){const params=new URLSearchParams({q:`name='${q(name)}' and '${parent}' in parents and trashed=false`,fields:'files(id,name)'});const j=await g(auth,'GET','https://www.googleapis.com/drive/v3/files?'+params);return j.files?.[0]?.id}
async function uploadFile(auth,name,mime,parent,bytes){const existing=await findFile(auth,name,parent);const meta={name,mimeType:mime,parents:[parent]};const boundary='foo_bar_baz_'+Date.now();const head=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(meta)}\r\n--${boundary}\r\nContent-Type: ${mime}\r\n\r\n`;const tail=`\r\n--${boundary}--`;const body=new Blob([head,bytes,tail]);const url=existing?`https://www.googleapis.com/upload/drive/v3/files/${existing}?uploadType=multipart&fields=id,name`:'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name';return await g(auth,existing?'PATCH':'POST',url,body,{'Content-Type':'multipart/related; boundary='+boundary});}
export async function onRequest({request,env}){if(request.method!=='POST')return new Response('Method not allowed',{status:405});let auth=dec(cookie(request,'IA_AUTH'));if(!auth)return new Response('Not signed in',{status:401});let setCookie=null;try{const r=await refresh(auth,env);auth=r.auth;setCookie=r.setCookie;const body=await request.json();const root=await ensureFolder(auth,env.DRIVE_ROOT_FOLDER_NAME||'Inspection App','root',{app:'asset-inspection'});const inspector=await ensureFolder(auth,auth.email,root,{inspector:auth.email});const fname=(body.inspection?.folderName||body.inspection?.id||'Inspection').replace(/[\\/:*?"<>|]+/g,'-');const inspection=await ensureFolder(auth,fname,inspector,{inspectionId:body.inspection?.id||''});let parent=inspection;const parts=(body.path||'file.bin').split('/').filter(Boolean);const filename=parts.pop();for(const p of parts)parent=await ensureFolder(auth,p,parent,{inspectionId:body.inspection?.id||''});const out=await uploadFile(auth,filename,body.mime||'application/octet-stream',parent,dataToBytes(body.content));return new Response(JSON.stringify({ok:true,file:out,inspectionFolder:inspection}),{headers:{'Content-Type':'application/json',...(setCookie?{'Set-Cookie':setCookie}:{})}})}catch(e){return new Response(e.message,{status:500,headers:setCookie?{'Set-Cookie':setCookie}:{}})}}
